application: kezu-sid
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  
- url: /images
  static_dir: images
  
- url: /css
  static_dir: css
  
- url: /_ah/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  #login: admin
  
- url: .*
  script: main.py
  
builtins:
  - datastore_admin: on