application: drawpad-appspot
version: 1
runtime: python
api_version: 1

handlers:
- url: /assets
  static_dir: assets
  
- url: /_ah/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: main.py
  
builtins:
- datastore_admin: on